import React,{useEffect,useState} from "react";
import * as api from "./googleSheetApi";

function Login({onLogin}){const [register,setRegister]=useState(false),[f,setF]=useState({}),[err,setErr]=useState("");
 const update=e=>setF({...f,[e.target.name]:e.target.type==="file"?e.target.files[0]:e.target.value});
 const submit=async e=>{e.preventDefault();setErr("");try{const x=register?await api.register({...f,terms_accepted:f.terms_accepted?"true":"false"}):await api.login(f);onLogin(x)}catch(x){setErr(x.message)}};
 return <main className="login"><section className="card registration-card"><h1>BLDCL e-Procurement</h1><p>{register?"Bidder Registration":"Bidder / Staff Login"}</p><form onSubmit={submit}>
{register&&<div className="registration-fields"><input name="name" placeholder="Full name" required onChange={update}/><input name="vendor_name" placeholder="Vendor name" required onChange={update}/><select name="vendor_type" required defaultValue="" onChange={update}><option value="" disabled>Vendor type</option><option>Company</option><option>Individual</option><option>Partnership</option><option>Joint Venture</option></select><input name="tpn_number" placeholder="TPN number" required onChange={update}/><input name="license_no" placeholder="License number" required onChange={update}/><label className="file-field">Trade license / Certificate of Registration<input name="trade_license" type="file" accept=".pdf,.jpg,.jpeg,.png" required onChange={update}/></label><textarea name="address_details" placeholder="Address details" required onChange={update}></textarea><textarea name="contact_details" placeholder="Contact details (phone, email, representative)" required onChange={update}></textarea><label className="terms"><input name="terms_accepted" type="checkbox" required onChange={update}/> I accept the terms and conditions</label></div>}
 <input name="email" type="text" placeholder="Email or username" required onChange={update}/><input name="password" type="password" placeholder="Password" required onChange={update}/>
 <button>{register?"Submit Bidder Registration":"Login"}</button></form>{err&&<div className="error">{err}</div>}<button type="button" className="link" onClick={()=>{setErr("");setRegister(!register)}}>{register?"Already registered? Login":"Register as bidder"}</button></section></main>}

function AdminDashboard({token,onLogout}){
 const blankForm={tender_id:"",title:"",category:"Goods",location:"",description:"",submission_deadline:"",opening_date:""};
 const [tenders,setTenders]=useState([]),[bids,setBids]=useState([]),[expandedBid,setExpandedBid]=useState(null),[form,setForm]=useState(blankForm),[items,setItems]=useState([{description:"",unit:"",quantity:"",estimated_price:""}]),[file,setFile]=useState(null),[message,setMessage]=useState(""),[error,setError]=useState(""),[editingId,setEditingId]=useState(null),[originalItemIds,setOriginalItemIds]=useState([]);
 const load=async()=>{try{const [tenderData,bidData]=await Promise.all([api.getTenders(token),api.getBids(token)]);setTenders(tenderData);setBids(bidData)}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[]);
 const updateForm=e=>setForm({...form,[e.target.name]:e.target.value});
 const updateItem=(index,e)=>setItems(items.map((item,i)=>i===index?{...item,[e.target.name]:e.target.value}:item));
 const editTender=t=>{setEditingId(t.id);setForm({...t,submission_deadline:t.submission_deadline?.slice(0,16),opening_date:t.opening_date?.slice(0,16)});setItems(t.items?.length?t.items.map(item=>({...item})):[]);setOriginalItemIds((t.items||[]).map(item=>item.id));setFile(null);setMessage("");setError("");window.scrollTo({top:0,behavior:"smooth"})};
 const cancelEdit=()=>{setEditingId(null);setForm(blankForm);setItems([{description:"",unit:"",quantity:"",estimated_price:""}]);setOriginalItemIds([]);setFile(null)};
 const create=async e=>{e.preventDefault();setError("");setMessage("");try{
	 const payload={...form,submission_deadline:new Date(form.submission_deadline).toISOString(),opening_date:new Date(form.opening_date).toISOString()};
	 const tender=editingId?await api.updateTender(token,editingId,payload):await api.createTender(token,payload);
	 for(const [index,item] of items.entries()) if(item.description){const itemPayload={description:item.description,unit:item.unit,quantity:item.quantity,estimated_price:item.estimated_price,line_no:index+1,tender:tender.id};if(item.id) await api.updateTenderItem(token,item.id,itemPayload);else await api.createTenderItem(token,itemPayload)}
	 for(const id of originalItemIds.filter(id=>!items.some(item=>item.id===id))) await api.deleteTenderItem(token,id);
	 if(file) await api.uploadTenderDocument(token,tender.id,file);
	 setMessage(editingId?`Tender ${tender.tender_id} updated.`:`Tender ${tender.tender_id} saved as draft.`);cancelEdit();await load();
 }catch(e){setError(e.message)}};
 const publish=async id=>{try{await api.publishTender(token,id);setMessage("Tender published successfully.");await load()}catch(e){setError(e.message)}};
 return <><header><strong>BLDCL Admin Console</strong><span><button onClick={onLogout}>Logout</button></span></header><main className="wrap admin-grid"><section className="card"><h2>{editingId?"Edit Tender":"Create Tender"}</h2>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<form onSubmit={create} className="admin-form">
 <div className="form-grid"><input name="tender_id" placeholder="Tender ID" required value={form.tender_id} onChange={updateForm}/><input name="title" placeholder="Tender title" required value={form.title} onChange={updateForm}/><input name="category" placeholder="Category" required value={form.category} onChange={updateForm}/><input name="location" placeholder="Location" value={form.location} onChange={updateForm}/><label>Submission deadline<input name="submission_deadline" type="datetime-local" required value={form.submission_deadline} onChange={updateForm}/></label><label>Opening date<input name="opening_date" type="datetime-local" required value={form.opening_date} onChange={updateForm}/></label></div><textarea name="description" placeholder="Tender description" value={form.description} onChange={updateForm}/>
 <h3>Priced Items</h3><div className="item-editor">{items.map((item,index)=><div className="item-row" key={index}><input name="description" placeholder="Item description" required value={item.description} onChange={e=>updateItem(index,e)}/><input name="unit" placeholder="Unit" value={item.unit} onChange={e=>updateItem(index,e)}/><input name="quantity" type="number" min="0" step="0.01" placeholder="Qty" required value={item.quantity} onChange={e=>updateItem(index,e)}/><input name="estimated_price" type="number" min="0" step="0.01" placeholder="Price" required value={item.estimated_price} onChange={e=>updateItem(index,e)}/><button type="button" className="danger" onClick={()=>setItems(items.filter((_,i)=>i!==index))}>Remove</button></div>)}</div><button type="button" className="secondary" onClick={()=>setItems([...items,{description:"",unit:"",quantity:"",estimated_price:""}])}>Add item</button>
 <label className="file-field">{editingId?"Replace tender document":"Tender document"}<input type="file" onChange={e=>setFile(e.target.files[0]||null)}/></label><button type="submit">{editingId?"Save Changes":"Save Tender Draft"}</button>{editingId&&<button type="button" className="secondary" onClick={cancelEdit}>Cancel Edit</button>}</form></section><section className="card"><h2>Managed Tenders</h2><table><thead><tr><th>ID</th><th>Title</th><th>Status</th><th>Items</th><th></th></tr></thead><tbody>{tenders.map(t=><tr key={t.id}><td>{t.tender_id}</td><td>{t.title}</td><td>{t.status}</td><td>{t.items?.length||0}</td><td><button onClick={()=>editTender(t)}>Edit</button>{t.status==="DRAFT"&&<button onClick={()=>publish(t.id)}>Publish</button>}</td></tr>)}</tbody></table></section><section className="card bid-board"><h2>BOQ / Financial Bid Board</h2>{bids.length===0?<p>No bids submitted yet.</p>:<table><thead><tr><th>Bidder</th><th>Tender</th><th>Reference</th><th>Status</th><th>Total</th><th></th></tr></thead><tbody>{bids.map(b=><React.Fragment key={b.id}><tr><td>{b.bidder_name}</td><td>{b.tender_reference}</td><td>{b.reference}</td><td>{b.status}</td><td>Nu. {Number(b.total_amount||0).toFixed(2)}</td><td><button onClick={()=>setExpandedBid(expandedBid===b.id?null:b.id)}>{expandedBid===b.id?"Hide BOQ":"View BOQ"}</button></td></tr>{expandedBid===b.id&&<tr><td colSpan="6"><table className="nested-table"><thead><tr><th>Sl</th><th>Description</th><th>Unit</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{(b.items||[]).map(item=><tr key={item.id}><td>{item.line_no}</td><td>{item.description}</td><td>{item.unit}</td><td>{item.quantity}</td><td>Nu. {Number(item.rate||0).toFixed(2)}</td><td>Nu. {Number(item.amount||0).toFixed(2)}</td></tr>)}</tbody></table></td></tr>}</React.Fragment>)}</tbody></table>}</section></main></>;
}

function App(){
 const [session,setSession]=useState(()=>{try{return JSON.parse(localStorage.getItem("bldcl_session")||"null")}catch{localStorage.removeItem("bldcl_session");return null}});
 const [tenders,setTenders]=useState([]),[selected,setSelected]=useState(null),[bid,setBid]=useState(null),[err,setErr]=useState("");
 const token=session?.token, user=session?.user;
 const load=async()=>{try{setTenders(await api.getTenders(token))}catch(e){if(e.status===401){localStorage.removeItem("bldcl_session");setSession(null);return}setErr(e.message)}};
 useEffect(()=>{if(token)load()},[token]);
 if(!session)return <Login onLogin={x=>{localStorage.setItem("bldcl_session",JSON.stringify(x));setSession(x)}}/>;
 if(user?.role==="Admin"||user?.role==="Procurement Officer")return <AdminDashboard token={token} onLogout={()=>{localStorage.clear();setSession(null)}}/>;
 const openTender=async t=>{try{const full=await api.getTender(token,t.id);setSelected(full);setBid(null)}catch(e){setErr(e.message)}};
 const participate=async()=>{try{const b=await api.createBid(token,{tender_id:selected.id,total_amount:0});setBid(b)}catch(e){if(e.bidId){setBid(await api.getBid(token,e.bidId));return}setErr(e.message)}};
 return <><header><strong>BLDCL e-Procurement</strong><span>{user.name} · {user.role}<button onClick={()=>{localStorage.clear();setSession(null)}}>Logout</button></span></header>
 <main className="wrap"><h2>Online Tendering Portal</h2>{err&&<div className="error">{err}</div>}
 {!selected?<section className="card"><h3>Active Tenders</h3><table><thead><tr><th>Tender ID</th><th>Title</th><th>Category</th><th>Deadline</th><th>Status</th><th></th></tr></thead><tbody>{tenders.map(t=><tr key={t.id}><td>{t.tender_id}</td><td>{t.title}</td><td>{t.category}</td><td>{new Date(t.submission_deadline).toLocaleString()}</td><td>{t.status}</td><td><button onClick={()=>openTender(t)}>View</button></td></tr>)}</tbody></table></section>
 :<TenderView tender={selected} bid={bid} token={token} onBack={()=>setSelected(null)} onParticipate={participate} onBid={setBid}/>}
 </main></>}

function TenderView({tender,bid,token,onBack,onParticipate,onBid}){
 const [items,setItems]=useState(tender.items||[]),[rates,setRates]=useState({}),[files,setFiles]=useState([]),[msg,setMsg]=useState("");
 useEffect(()=>{if(bid?.items?.length)setRates(Object.fromEntries(bid.items.map(item=>[item.tender_item||item.id,item.rate])))},[bid]);
 const total=items.reduce((s,x)=>s+(Number(rates[x.id]||0)*Number(x.quantity||0)),0);
 const makeBid=async()=>{try{await onParticipate()}catch(e){setMsg(e.message)}};
 const save=async()=>{try{const b=await api.saveBidItems(token,{bid_id:bid.id,items:items.map(x=>({boq_item_id:x.id,description:x.description,unit:x.unit,quantity:x.quantity,rate:Number(rates[x.id]||0),amount:Number(rates[x.id]||0)*Number(x.quantity||0)}))});onBid(b);setMsg("BOQ saved") }catch(e){setMsg(e.message)}};
 const upload=async e=>{const file=e.target.files[0];if(!file||!bid)return;try{const d=await api.uploadDocument(token,{parent_id:bid.id,name:file.name,file});setFiles([...files,d]);setMsg("Bid document uploaded") }catch(x){setMsg(x.message)}};
 const submit=async()=>{try{const b=await api.submitBid(token,bid.id);onBid(b);setMsg("Bid submitted successfully")}catch(e){setMsg(e.message)}};
 return <section className="card"><button onClick={onBack}>← Back</button><h2>{tender.title}</h2><p><b>{tender.tender_id}</b> · {tender.category} · {tender.location}</p><p>{tender.description}</p><h3>Tender Documents</h3><ul>{(tender.documents||[]).map(d=><li key={d.id}><a href={d.file} target="_blank" rel="noreferrer" download>{d.name} - Download</a></li>)}</ul>
 {!bid?<button onClick={makeBid}>Participate in Tender</button>:<><h3>BOQ / Financial Bid</h3><table><thead><tr><th>Sl</th><th>Description</th><th>Unit</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.line_no}</td><td>{x.description}</td><td>{x.unit}</td><td>{x.quantity}</td><td><input type="number" disabled={bid.status!=="DRAFT"} value={rates[x.id]||""} onChange={e=>setRates({...rates,[x.id]:e.target.value})}/></td><td>{(Number(rates[x.id]||0)*Number(x.quantity||0)).toFixed(2)}</td></tr>)}</tbody></table><h3>Total: Nu. {total.toFixed(2)}</h3>
 {bid.status==="DRAFT"&&<><button onClick={save}>Save BOQ</button><label className="upload">Upload Bid Document<input type="file" onChange={upload}/></label><button onClick={submit}>Submit Bid</button></>}
 {bid.status==="SUBMITTED"&&<div className="success">Bid submitted: <b>{bid.reference}</b><br/>Submission time: {new Date(bid.submitted_at).toLocaleString()}</div>}</>}
 {msg&&<div className="notice">{msg}</div>}</section>}

export default App;
